### ISSUE TITLE
Questions about examples

### ISSUE THREAD

**Issue by HongHuangNeu** [ArangoDB-Community/arangodb-tinkerpop-provider#33]
Hi! Is there any examples on how to use this tinkerpop provider to access ArrangoDB via java API? There are not even related test cases in the repository and the example in wiki seems quite misleading.

**Comment by arcanefoam** [comment]
Hi,
The lack of test cases is because the implementation is tested against the official Tinkerpop Test Suite. 
What do you find misleading in the "Using ArangoDBGraph via the Tinkerpop API" section on the Wiki Home page? If you can tell me what are we missing we can work together to put it there.

**Comment by marcelalburg** [comment]
Hello, i'm using ArangoDB 3.4 and your plugin from the maven repo in version 2.0.0.

```
        PropertiesConfiguration configuration = new PropertiesConfiguration();
        configuration.setProperty("arangodb.hosts", "127.0.0.1:8529");
        configuration.setProperty("arangodb.user", "root");
        configuration.setProperty("arangodb.password", "");

        configuration.setProperty("gremlin.graph", "com.arangodb.tinkerpop.gremlin.jsr223.ArangoDBGramlinPlugin");
        Properties arangoProperties = ConfigurationConverter.getProperties(configuration);


                // create a ArangoDB graph
        // BaseConfiguration conf = builder.build();
        Graph graph = GraphFactory.open(arangoProperties);
        gts = new GraphTraversalSource(graph);
```
(yes, in the 2.0.0 version there is the spelling error "Gramlin" instead of "Gremlin" - it's fixed in the master already)

and i got the error:

`
GraphFactory can only instantiate Graph implementations from classes that have a static open() method that takes a single Apache Commons Configuration argument - [class com.arangodb.tinkerpop.gremlin.jsr223.ArangoDBGramlinPlugin] does not seem to have one
`

do you've a working gremlin example somewhere running ?

Thanks a lot.

Marcel

**Comment by arcanefoam** [comment]
Hi Marcel,

Have you tried the code from the readme? I have added an ArangoDBConfigurationBuilder to facilitate the creation of the configurations. Can you try that example and let me know if it fails?

**Comment by marcelalburg** [comment]
Hello and thanks for the fast answer. If i write the code from the Readme file in a simple junit test, i get the error:

`java.lang.RuntimeException: Configuration must contain a valid 'gremlin.graph' setting`

Thanks.
M

**Comment by arcanefoam** [comment]
Thanks for spotting this. There is actually a line missing in the readme code! This is the line:
`conf.addProperty(Graph.GRAPH, ArangoDBGraph.class.getName());` after the configuration is built. The Graph.GRAPH constant is "gremlin.graph". 

BTW, the class name you are using is for the Gremlin Console driver :).

I will add this line to the example.

**Comment by marcelalburg** [comment]
Thanks, if i add you line:

```
import com.arangodb.tinkerpop.gremlin.structure.ArangoDBGraph;
conf.addProperty(Graph.GRAPH, ArangoDBGraph.class.getName());
```

the following error occurs: 

`java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class com.arangodb.tinkerpop.gremlin.structure.ArangoDBGraph]
`

It looks like, that the 2.0.0 version in the maven repo differ much from the current master.

M

**Comment by arcanefoam** [comment]
Interesting. I will look into this and see if I need to publish a new version with the changes. I will keep you posted.

**Comment by arcanefoam** [comment]
Tests are running fine in my machine. Can you post (or mail me) the complete stack trace?

**Comment by marcelalburg** [comment]
Uhh, i read the full stack trace by myself and later on, i've seen that a 401 happens. So thanks for you help and that we figure out that a line was missing in the readme. It works now !

Thanks

**Comment by arcanefoam** [comment]
I will close this for now as the readme and wiki have been updated since.
