### ISSUE TITLE
AQL: too many collections/shards

### ISSUE THREAD

**Issue by kuzeko** [ArangoDB-Community/arangodb-tinkerpop-provider#63]
I'm trying to load a graph with tinkerpop, and got this error:

```
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 1522 - AQL: too many collections/shards (while parsing)
```

what does it mean?

The graph I'm loading has some many thousands node labels and edge types

This is where it happens:
```
g.V()
        .has(ds.uid_field, edge.source)
	.outE(edge.label)
	.where(__.inV().has(ds.uid_field, edge.target))
	.next().id()
```

**Comment by dothebart** [comment]
the number of collections outdone for this error message is 2048. 
@arcanefoam may know more about the other implementation details in this driver.

**Comment by kuzeko** [comment]
It means arango cannot load more than 2048 edge or node labels?

**Comment by dothebart** [comment]
if you have each of them in your own collection - then you can't do that. 
Collections are what Tables are in SQL solutions, so that is quiet a lot.

**Comment by arcanefoam** [comment]
Seems more like an Arango exception due to limits mentioned by Wilfred than
the tinker pop implementation.

**Comment by kuzeko** [comment]
It seems I have no direct control on where Arango wants to store edge/node labels...

**Comment by arcanefoam** [comment]
Closing this as bug for feature request was opened.

**Comment by kuzeko** [comment]
I would suggest this as well to convert to a feature that catches that error and outputs a more meaningful error message
