### ISSUE TITLE
Decouple shouldPrefixCollectionNames with DB creation

### ISSUE THREAD

**Issue by edenaharoni** [ArangoDB-Community/arangodb-tinkerpop-provider#71]
Currently the ctor of the ```ArangoDBGraph``` is creating an```ArangoDBGraphClient``` with sending it the ```shouldPrefixCollectionNames``` as a boolean for the ```createDatabase``` param. 
I think this should be decoupled with new configuration added to the ```ArangoDBConfigurationBuilder``` named ```shouldCreateDatabase``` or even add it to the ```.dataBase``` method as a ```boolean``` param.

**Comment by arcanefoam** [comment]
The shouldPrefixCollectionNames flag coupled with creating or reusing an existing database. That is, 

- `shouldPrefixCollectionNames == false` -> reuse existing db+graph  -> `createDatabase = false`
- `shouldPrefixCollectionNames == true` -> create new db+graph  -> `createDatabase = true`

Note that the current implementation does not cope well with existing databases+graphs. #38 addresses this issue.
