### ISSUE TITLE
lambdas and python

### ISSUE THREAD

**Issue by Pippin555** [ArangoDB-Community/arangodb-tinkerpop-provider#72]
not an issue, but a question:

At this moment I am half way the 'Practical Gremlin' course by Kelvin R. Lawrence.
I have not yet used this provider to actually connect to ArangoDB yet.
I see that for some functions I need lambda statements (for instance for regular expressions). When I try that for gremlin_python and the Gremlin Server from Tinkerpop I get the following message:
"gremlin-python is not an available GremlinScriptEngine"
Will I be able to use lambda statements when I have an actual connection to ArangoDB or is it not supported (like AWS Neptune) for security reasons?

**Comment by dothebart** [comment]
If I get that correctly, this would strive to execute code inside of the database? 
Arangodb doesn't offer this possibility.

**Comment by Pippin555** [comment]
I am not sure where the code is executed, I see examples of Java and Python in the examples from "Practical Gremlin". Knowing this I do not need to spend time on the examples that use lambdas. There are other (but maybe less efficient) ways to get to a goal.
